### ISSUE TITLE
XML Output Style

### ISSUE THREAD

**Issue by michidk** [wojtpl2/ExtendedXmlSerializer#119]
I'm using the xml serializer to generate configuration files, which can be edited by the user/developer.

1. Is it possible to "beautify" the xml code, so that not everything is squashed into one line?
2. And is it possible to somehow define the element order (so that either its the same as the order as the appearance in the c# source code or it can be defined using an attribute: [XMLElement("Element", 5)]?
3. Is it also possible to prevent the serializer from outputting the capacity when serializing lists?

If not, then see this as a feature request :)

**Comment by Mike-EEE** [comment]
Cool, glad to hear that you got things running!

1. Indeed.  We went through a very intensive performance tuning phase during this project.  Part of that performance is how we format by default.  Less whitespace means better performance.  Although I suspect we are going to get a lot of questions in regard to this so we'll make this part of the documentation, too.  In any case, yes, you can certainly override this in the `[Serialize](https://github.com/wojtpl2/ExtendedXmlSerializer/blob/v2.0.0/src/ExtendedXmlSerializer/ExtensionModel/Xml/Extensions.cs#L126)` override by passing in a `XmlWriterSettings` that has the formatting set to your preferences.
1. Yes, you can. :)  We support the native `XmlElementAttribute.Order` and we also have the ability to configure this via [configuration as well](https://github.com/wojtpl2/ExtendedXmlSerializer/blob/v2.0.0/test/ExtendedXmlSerializer.Tests/Configuration/ConfigurationContainerTests.cs#L153).
1. I like your questions because we've got answers to them. 😎  You can indeed do this as well.  [An example can be found here](https://github.com/wojtpl2/ExtendedXmlSerializer/blob/v2.0.0/test/ExtendedXmlSerializer.Tests/ExtensionModel/Content/Members/AllowedMembersExtensionTests.cs#L36).  Please note however that the `Capacity` field can help with performance a smidge during initialization if you have large collections.  It's basically telling the list that you have x-number of items so build an array that will have that many.  Otherwise, what it will do is start out with an array of 4 items, and then past that, double it to (I believe) 8, then 16, etc, until it can account for all items.  Each one of these is a new object allocation and adds to the memory pressure of your application.

**Comment by michidk** [comment]
Awesome!
The settings regarding 1. and 2. are per type right? Is it possible to set those globally per serializer-config for all types?

**Comment by Mike-EEE** [comment]
Ah... the order setting is per member.  So it's member-based and not type-based, if that makes sense.  I'll need more context on what you're aiming to achieve to provide more guidance here.

**Comment by michidk** [comment]
What I want to achieve is basically:
ConfigurationContainer.SetOrder(Order.Alphabetical) which e.g. sorts all nodes of the output of Serialize alphabetical (or Order.Source which sorts them like their appearance in the source code). I just want to set these order rules for all types and all members (per Configuration/Output).

In my case I want to just want to have the order of the nodes to be the same of the members in the class file for every class by adding just one line of code.
If I have a class with:
```
public String Name;
public String Desc;
```
I want a xml string with:
```
<..>
<Name>...</Name>
<Desc>...</Desc>
</..>
```
Because thats the order they appear in the source code, and not:
```
<..>
<Desc>...</Desc>
<Name>...</Name>
</..>
```

**Comment by Mike-EEE** [comment]
So what you are describing here is a strategy mechanism for ordering members.  Currently we support a simple ordering mechanism that is member-by-member basis.  However, there's nothing stopping you from creating a cool extension (or extension methods) that would make this more sophisticated to perform what you are describing.  You could basically yield a set of numbers then pass them into the [`IMemberConfiguration.Order`](https://github.com/wojtpl2/ExtendedXmlSerializer/blob/v2.0.0/src/ExtendedXmlSerializer/ExtensionModel/Types/Extensions.cs#L65) extension method after they are determined.  Make sense?

**Comment by michidk** [comment]
Correct, that's exactly what I need. 
Right now, I'd have to add the order attribute to every element. Would be great if that could be done automatically by applying different strategies. 

Sadly I didn't find the time yet, to fully dive into EXML and how it works. I just saw that it uses a lot of extension methods, which I don't use that often (I only use them in my projects to add functionality to other libraries).

I probably gonna use the attribute-way for now.

**Comment by Mike-EEE** [comment]
Indeed, there are a lot of extension methods for the configuration api especially.  It was my first (woeful) attempt at a fluent API.  I am currently rebuilding it to be more traditional, lol.  Should be done by alpha 7.

Just to be sure here, there is nothing inherent with EXS in regards to what you would like to accomplish in regards to a mass ordering strategy.  This is something you could achieve on your own by custom logic that you provide.  The only thing that EXS expects is an integer value for that member, and from there it orders the members from that.

Although, if you're wanting to order based on the appearance in source code, it might be a little tricky.  The only thing I can think of is getting a static analyzer like cecil or even Roslyn.  Seems like a lot of work for such a simple task.  You might be better off using an attribute, regardless. :)

**Comment by Mike-EEE** [comment]
I should also mention that by default we are not ordering by member name but by the [Member.MetadataToken](https://msdn.microsoft.com/en-us/library/system.reflection.memberinfo.metadatatoken(v=vs.110).aspx) property.

**Comment by Mike-EEE** [comment]
Ah, got my issues mixed up.  This is the thread with the ordering.  Same thing goes, though. If you run into any issues implementing this and need assistance from us we can take a look into it.  Furthermore if you have something you'd like to contribute, please send us a PR and we will check it out. 👍

**Comment by umutesen** [comment]
The link to example does not seem to show how to exclude the capacity from the rendered xml. Can you provide an example?

**Comment by Mike-EEE** [comment]
Hey @umutesen ... linking you to #171 in case anyone else is wondering. 😄
