### ISSUE TITLE
EnableDeferredReferences extension don't work

### ISSUE THREAD

**Issue by wojtpl2** [wojtpl2/ExtendedXmlSerializer#131]
```C#
var config = new ConfigurationContainer();
config.EnableDeferredReferences();
config.Type<IElement>().EnableReferences(p => p.Id);                      
config.Type<Section>().EnableReferences(p => p.Id);
...
config.Type<Building>().EnableReferences(p => p.Id).Create();
                        
var serializer = config.Create();
```
Section have reference to building. But buildings can exists without Sections.

I keep all elements in one List<IElement>.

EnableDeferredReferences was added in #87 and its not work properly.

**Comment by Mike-EEE** [comment]
Ah, OK.  Is it possible to get a failing test committed so I can take a look into this one?

**Comment by wojtpl2** [comment]
OK I'll try to create failing test.

**Comment by wojtpl2** [comment]
I've added failing test.

**Comment by Mike-EEE** [comment]
Cool... I went ahead and fixed it.  It will work for now, but it is not a good long-term solution.  I can see extensions being grouped together based on usage rather than just an ordered list.  It's all part of the configuration API, so maybe in v3 with a clean sweep at some point, we can fix this too. 👼

**Comment by Mike-EEE** [comment]
This should now be addressed.  Please let me know if there is anything further on this issue that needs to be addressed/implemented.
