### ISSUE TITLE
Question about xml namespaces

### ISSUE THREAD

**Issue by wojtpl2** [wojtpl2/ExtendedXmlSerializer#140]
I have model like this:
```c#
	public class Example
	{
		public IModelObject Model { get; set; }
	}

	public interface IModelObject
	{
	}

	public class Model : IModelObject
	{
		public string Name { get; set; }
	}
```
and then I serialize object:
```C#
var serializer = new ConfigurationContainer().Create();
var obj = new Example
				{
					Model = new Model { Name = "name" }
				};
var xml = serializer.Serialize(obj);
```
xml look like:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Example xmlns="clr-namespace:ExtendedXmlSerializer.Samples.Simple;assembly=ExtendedXmlSerializer.Samples">
	<Model xmlns:exs="https://extendedxmlserializer.github.io/v2" exs:type="Model">
		<Name>name</Name>
	</Model>
</Example>
```

The namespace on model element `xmlns:exs="https://extendedxmlserializer.github.io/v2"` is correct, isn't it? Why Example doesn't have this namespace?

**Comment by wojtpl2** [comment]
It is example from https://stackoverflow.com/a/39633618/4809321

**Comment by Mike-EEE** [comment]
Ah, because of the interface that is `Example.Model`.  Since it is not a concrete type, but an abstract/interface one, we inject the `exs:type` attribute at the level at which it occurs, so that it will properly deserialize when it is read back in during deserialization.

If you want this to be at the root, you can make use of [optimized namespaces](https://github.com/wojtpl2/ExtendedXmlSerializer#optimized-namespaces).

**Comment by wojtpl2** [comment]
Ok, now I understand.
Thanks
