### ISSUE TITLE
Add Support for Configuration Profiles

### ISSUE THREAD

**Issue by AQuentin2033** [wojtpl2/ExtendedXmlSerializer#148]
Hi,

I have a few dozen types in a custom library and I would like to offer support for users of ExtendedXmlSerializer without explicitly adding a reference to it from my library.  Is it possible to generate a configuration with all the type specific settings for the library and provide this (binary or xml) configuration to the library user in a single initialization step? (instead of pages of fluid configuration)

Alternatively is it possible to precompile the serialization similar to how Marc handles it with [protobuf-net ](http://blog.marcgravell.com/2012/07/introducing-protobuf-net-precompiler.html)?

thanks

**Comment by Mike-EEE** [comment]
Haha... a configuration for the configuration?  An XML for the XML?  A DREAM WITHIN A DREAM??? :)  Sure, it's an open source project, anything is possible. 😄 

I just read that link.  That's a cool concept for sure.  Essentially you're creating configuration profiles which are applied to a set of types and then one of these profiles is applied to a `ConfigurationContainer` so that you don't have to have a mountain of code to do the same.

Incidentally we're describing Xaml here and it's one of the reasons why I <3 it so much.  You could conceivably describe this profile (or profiles) in Xaml and then compile it as a class, applying then it to a `ConfigurationContainer`.  Unfortunately [System.Xaml is not cross-platform](https://github.com/dotnet/corefx/issues/5766) ATM. 😢

**Comment by wojtpl2** [comment]
It is great idea. We can create similar solution like Autofac:
http://autofaccn.readthedocs.io/en/latest/configuration/xml.html

**Comment by Mike-EEE** [comment]
Yeah the problem though is that we're basically requiring at least two `ConfigurationContainer`'s now: 1 for configuration and 1 (or more) for object graphs.  We do NOT want to load XML documents and parse them element by element (and/or attribute by attribute) because that is exactly what EXS is meant to avoid.  I think the best way of doing this is to have a (properly configured) `ConfigurationContainer` singleton that is specifically used to reading and writing configuration elements/graphs which are then applied to additional `ConfigurationContainer`s.

This might actually be straight-forward.  I will see if we can get this in for 2.1.

**Comment by Mike-EEE** [comment]
OK check this out:
https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue148Tests.cs

Super simple example here.  I started designing this, and thought: do we need an external file format at all?  Ultimately, in that example above, the file gets compiled into a particular type of configured container.  The same can be accomplished by using an alteration as demonstrated in the test.

We could also introduce a file format as well, if that makes sense.  I want to make sure that is valuable before I start down that path because it is going to be a bit labor-intensive.  Essentially, we will need to make a command for every extension that we have from our `IConfigurationContainer`, `ITypeConfiguration` and `IMemberConfiguration`.  In fact, what we would probably end up doing is creating these commands and then point all of the extension methods to the newly created commands.

But before we do that... what is everyone's thought on simply using defined profiles as demonstrated in the tests?  You can even combine them as demonstrated by the `VerifyComposite` test.  Do we think that will be sufficient for now or are we looking/expecting an actual file to be used.  I can see a file format being useful if there's tooling involved, but ATM there is no such initiative (but would be super cool to have!).

Anyways, discuss. 😄

**Comment by AQuentin2033** [comment]
Hi Mike,

Not sure I am following exactly but if I understand for my library (which for simplicity I will call Glibrary)
  - I would create a separate assembly referencing ExtendedXMLSerializer and Glibrary
  - create a class which implements IConfigurationProfile and provides the serialization rules for Glibrary
Then either:
   - provide that assembly as an optional extension to Glibrary users
or
   - serialize that object using ExtendedXMLSerializer and provide that serialization file to Glibrary users who want to use xml serialization.

Then my users would
 - Reference ExtendedXMLSerializer
-  Then depending upon the option above either:
     - reference my extension library created above
   or 
     - deserialize the profile class using defaults
 - then create a new serializer with the corresponding profile class which they would use for serializing/deserializing Glibrary types

This could work.

On the other hand, since I originally posted the above request a few things have changed for me.  Not sure if its entirely relevant but in order for us to support protobuf, json and DataContract serialization for Glibrary we ended up needing to use surrogates.  As a result these surrogate types are simplistic, have the Serializable and DataContract attributes and have implicit conversions to and from the real types.  Additionally I have separate implementations for both ISerializationSurrogateProvider and ISerializationSurrogate (MS made a bit of a mess of this).  So in theory if ExtendedXMLSerializer supports those attributes then I really only need to be able to provide to the ExtendedXMLSerializer a list of type pairs or an ISerializationSurrogate or an ISerializationSurrogateProvider to use for surrogate substitution rather than a whole configuration -- sorry a bit of a tangent and although not as flexible perhaps it might be less work to implement and maintain than remapping all your configuration items to commands.

Honestly either way would work for me.  If I wasn't obliged to use surrogates then the first would be better but since I needed to make them, the second would let my users use ExtendedXMLSerializer on my library without me needing to do anything special (beyond what I have already done for other serialization)

Adam

**Comment by Mike-EEE** [comment]
Cool, thank you for providing more context around this.  A couple considerations here.

1. If you make your deliverable a nuget package (either on nuget or in a private package feed within your organization), ExtendedXmlSerializer (and all of its dependencies) automatically come along for the ride.  So your users would then reference this package (e.g. `Glibrary.Serialization`) really that is the only step outside of calling `ConfiguredContainer.New<Profile>()` to get the configured serializer that has been properly configured for all the types in your domain.
2. I am familiar with surrogates and that is exactly the kind of strategy we're aiming to eliminate here. 😄 Ideally/ultimately we should be able to serialize any object in the universe without having to resort to such clumsy and repetitive (not to mention time-consuming and therefore expensive) approaches.  Just to be sure, you're saying that you have to use these surrogates for integration with other areas and domains, correct?  That is, you have one application serializing in protobuf, and maybe another serializing in json, etc?  From our perspective, you should be able to serialize _any_ object in the .NET domain with ExtendedXmlSerializer (and if you can't, then easily do so by creating an extension), so want to make sure we're not the bottleneck here.
3. Just thinking about this, but we could also add another `ConfigurationContainer` as well, something like `ConfigurationContainer<T>` where `T` is a `IConfigurationProfile` and it would perform the configuration for you.  That way, in your distribution assembly, you would have a class like so:

```
public sealed class SerializationConfiguration : ConfigurationContainer<Profile> {}
```

And then consumers would simply have to do:

```
var serializer = new SerializationConfiguration().Create();
```

**Comment by Mike-EEE** [comment]
4. If EXS is not the bottleneck we should be able to make an extension that provides `ISerializationSurrogate*` support no problem, btw.  Actually since I am all caught up with everything else on my plate I will start working on that now. 😉

**Comment by Mike-EEE** [comment]
FWIW @AQuentin2033 I just added a new `ConfiguredSerializer` that improves further on the above.  You can see an example here:
https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue148Tests.cs#L38-L46

Essentially now boiled down to:
`var serializer = new Serializer();`

Where `Serializer` would be your extended serializer pointing to a configuration profile:
https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue148Tests.cs#L54

**Comment by AQuentin2033** [comment]
Thanks for being so responsive Mike, let me try and answer.

1 -  So far I have very few users of the library who actually want to use xml serialization (only 1 request so far) so I don't really want to add a dependency for the vast majority who don't need it.   Same reason I don't want to add all the Xml tags in the various classes to have it serialize correctly using the .net framework Xmlserializer.
2 - Yes the surrogates were created to handle json and protobuf serialization which couldn't handle the objects as is.  In the case of json it was for two reasons, firstly the in-memory format of many of the types is not optimal for storage or transfer and secondly we did not want a dependency on json for those users who have no need of json serialization.  For protobuf it was mainly due to its inability to serialize some of our types.  Having made the surrogates - it made serialization for DataContracts easier so I used them for that too.   Since I have very little say over the serialization methods selected by the library users surrogates seemed like the best compromise.
3 - I like :)
4 - Ok Great :)
5 - that's pretty much as simple as it gets unless you take into account 1 but I'm also completely ok putting that in a separate assembly for the clients who need xml serialization to use.

**Comment by Mike-EEE** [comment]
Coooool @AQuentin2033 ... the goal being here to show/demonstrate to all that XML is still open for business and can be used to serialize anything easily while maintaining the integrity and structure of your existing classes. 😉 #MakeXMLGreatAgain heh heh.

**Comment by Mike-EEE** [comment]
Closing this issue as it has been deployed in 2.1.0: #162

Please feel free to open an issue if you encounter any further problems.
