### ISSUE TITLE
How do you implement the deserialization? 

### ISSUE THREAD

**Issue by dodyg** [wojtpl2/ExtendedXmlSerializer#151]
Do you use XmlReader or do you use DOM? 

Will this library suitable to deserialize complex XML schema such as Open NDC Schema (http://www.iata.org/whatwedo/airline-distribution/ndc/Pages/schema-download2.aspx)?

**Comment by Mike-EEE** [comment]
Hi @dodyg this project uses `XmlWriter` and `XmlReader` for its serialization/deserialization purposes.  As for XML schemas, that is a good question.  I would say that this project is more meant and designed to serialize/deserialize POCO's (plain ol' CLR objects) rather than to deal with data documents.  It might be possible to create a POCO that represents your data document and use it for serialization/deserialization.  It should make your overall design simpler, too. 😄

**Comment by dodyg** [comment]
OK thanks for the clarification.
