### ISSUE TITLE
Using multiple custom serializers for complex type

### ISSUE THREAD

**Issue by joehmchan** [wojtpl2/ExtendedXmlSerializer#154]
First of all, thank you for your good work and I found this library useful.
I ran into a situation that needs to implement multiple custom serializers.

```
public class ParentType {
   public ChildType Child { get; set; }
}

public class ParentTypeSerializer : IExtendedXmlCustomSerializer<ParentType> {
    public void Serializer(XmlWriter writer, ParentType obj) {
          // How to tell this serializer that calls ChildTypeSerializer?
          // writer.WriteValue(obj.Child);
    }
}

public class ChildTypeSerializer : IExtendedXmlCustomSerializer<ChildType> {
    public void Serializer(XmlWriter writer, ChildType obj) {
          // Writer does something here
    }
}

// Registration
var serializer = new ConfigurationContainer()
    .Type<ParentType>()
    .CustomSerializer(new ParentTypeSerializer())
    .Type<ChildType>()
    .CustomSerializer(new ChildTypeSerializer())
    .Create();
```

If I got a customer serializer for both ParentType and ChildType, how do parent serializer ask ChildTypeSerializer to handle obj.Child property based on the type?

**Comment by wojtpl2** [comment]
Good question! It should be supported.

**Comment by Mike-EEE** [comment]
Indeed, this is a component from v1 that has carried over into v2.  I am taking a look into overriding member-based serialization for #150 ... I'll see if I whip something up for this as well.

**Comment by joehmchan** [comment]
@Mike-EEE, the reason I hitting this issue is that some of the class string members need to be wrapped by CData tag. It turns out that writing custom serializer is the only way to do so.

Sorry for my limited understanding on the whole project's source codes. Probably it is better to write extension method to tackle that issue.

**Comment by Mike-EEE** [comment]
Ah!  Well then, fixing #150 will address your ills here.  There is indeed a lot of code within this project.  I got a little crazy at times last year putting it together. 👼 I would probably make some different design decisions today but it took going through then to get to now.  Such is the nature of software, and life for that matter! 😄 

The CDATA issue is actually pretty involved, because it will involve adding a method to our `IFormatWriter` interface or some equivalent modification.  My free time this month has been smothered by real life and client work.  I hope to have that resolved in the next week (as I have been saying for that past two weeks haha), and if not we might have to start leaning on the community here to help out with some of these tasks.  I am really hoping I can get back to this though.  Trust me, it's stressing me out!

**Comment by Mike-EEE** [comment]
Alright, I've just committed an improvement that addresses this and a couple of other issues around registering serializers around types.  The best example of this is here:
https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue154Tests.cs#L50-L64

You can now reference a type as the serializer, and that type can hold registered dependencies (such as the global `ISerializers` class or the `ICustomXmlSerializers` that can get other serializers based on types.  Here is an example:
https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue154Tests.cs#L174-L186

Again this works for both type-registration and member-registration.  The `IExtendedXmlCustomSerializer` is for xml-based serialization (v1), but we also have the `ISerializer` which is sort of the root serialization object used in v2.  This can be used with the `Register` extension method as described here:
https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue154Tests.cs#L66-L81

Let me know if you have any questions around any of this. :)

**Comment by Mike-EEE** [comment]
Closing this issue as it has been deployed in 2.1.0: #162

Please feel free to open an issue if you encounter any further problems
