### ISSUE TITLE
Support for ISerializationSurrogate

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#161]
As per https://github.com/wojtpl2/ExtendedXmlSerializer/issues/148#issuecomment-361289941

**Comment by Mike-EEE** [comment]
Alright @AQuentin2033 I have been checking this out.  In #148 you state:

> Additionally I have separate implementations for both ISerializationSurrogateProvider and ISerializationSurrogate (MS made a bit of a mess of this). So in theory if ExtendedXMLSerializer supports those attributes then I really only need to be able to provide to the ExtendedXMLSerializer a list of type pairs or an ISerializationSurrogate or an ISerializationSurrogateProvider to use for surrogate substitution 

Can you add a little more context around this? I cannot seem to find `ISerializationSurrogateProvider` on the interwebs.  Also, you mention these are attributes, but are interfaces, correct?  I am wanting to make sure we support the right workflow here.  From what I can tell you create a new `SurrogateSelector` and then register your surrogates with that, then assign the surrogate to a formatter (like `BinaryFormatter`).

Even with all of this, I have to say that with ExtendedXmlSerializer you should not have a need for a surrogate at all.  You should be able to serialize and deserialize the .NET object as-is, without the need for surrogates and/or attributes.  I was thinking we could integrate with these interfaces, but in order to do so we would have to introduce a `StreamingContext` and `SerializationInfo`, and work with them accordingly.  I am pretty sure we can serialize/deserialize any object graph you have without having to do this, but I could be misunderstanding how you're going about this. 😄

**Comment by AQuentin2033** [comment]
laugh, yes its not so obvious, took me a while to get my head around what the framework people intended with it.  Let me try and explain

### [ISerializationSurrogateProvider](https://msdn.microsoft.com/en-us/library/system.runtime.serialization.iserializationsurrogateprovider(v=vs.110).aspx)
This is a .net standard 2.0/.net 4.7.1 interface
First a user passes an implementation of ISerializationSurrogateProvider to the serializer (config step)
e.g. DataContracts uses an extension method called SetSerializationSurrogateProvider on the serializer
```
            var serializer = new DataContractSerializer(item.GetType());
            serializer.SetSerializationSurrogateProvider(new MySurrogateProvider());
```

When the serializer is due to serialize a given type in an object graph, if a surrogate provider has been registered it calls the method GetSurrogateType to determine the to-be serialized output type.  It then calls GetObjectToSerialize passing the object which is due to be serialized and the type it should be converted into (obtained by called GetSurrogateType).  This method call should return either a correctly constructed surrogate or the original object passed.  The serializer then processes the returned object as it would have normally.

During deserialization the process occurs in reverse.  The serializer decodes the serialization into the surrogate object.  The serializer then calls GetDeserializedObject on the surrogate provider passing the surrogate type it has and the expected return type.  This method converts the object back to a native type object and returns it to the serializer who then returns it as normal.

### [ISerializationSurrogate](https://msdn.microsoft.com/en-us/library/system.runtime.serialization.iserializationsurrogate(v=vs.110).aspx)
and [SurrogateSelector](https://msdn.microsoft.com/en-us/library/system.runtime.serialization.surrogateselector(v=vs.110).aspx)
Available since .net 1.1 but all the more quirky for it

A serializer would take an [ISurrogateSelector](https://msdn.microsoft.com/en-us/library/system.runtime.serialization.isurrogateselector(v=vs.110).aspx) as a configuration item

To deserialize an object graph for each object in the serialization chain (obtained by calling GetNextSelector() in a loop)  it calls GetSurrogate passing the type to be serialized, a streamingcontext with any additional configuration information, and expects as an out parameter the ISurrogateSelector which returned the SerializationSurrogate (typically "this" but not always)  The return value is the ISerializationSurrogate which will convert the object.

The ISerializationSurrogate has two methods, GetObjectData for serializing the object and SetObjectData for deserializing the object.  From the serializer's point of view GetObjectData provides a list of fields and values in a SerializationInfo object to use in constructing the serialized contents.  Likewise when deserializing, the serializer decomposes the serialization stream into a SerializationInfo object that gets converted to a real object in SetObjectData.  As you noticed in the article you linked, it should create an empty object first and pass it as the first parameter, the user of SetObjectData may either update that object and return null, or return a new object.  Odd semantics but its a left over from .net 1.1

So having typed all this out and thought about it - from this libraries point of view I think it only makes sense to add support for ISerializationSurrogateProvider.

**Comment by Mike-EEE** [comment]
WOW... thank you for taking the time to thoroughly explain all of that @AQuentin2033.  I am in full agreement that `ISerializationSurrogateProvider` is the much better option.  I am of course apt to support it as not only is a more current/up-to-date implementation, but also (and because of this) makes more sense. 😉 I will look into seeing if I can make this work on our side.  If it is structured how I think it's structured, then it should be relatively easy to implement. 🤞

**Comment by Mike-EEE** [comment]
OK @AQuentin2033 check it out:
https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue161Tests.cs

Please take a look over that and see if that is what you are expecting.  Please also verify that my passing of types to `GetObjectToSerialize` and `GetDeserializedObject` are as expected here:
https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/src/ExtendedXmlSerializer/ExtensionModel/SurrogatesExtension.cs#L93-L104

Also, please note that in order for this to work, the target application must either be .NET Core 2.0 or .NET Framework 4.7.1.  If you are using a framework that is less than 4.7.1, everything in ExtendedXmlSerializer works unless you make a call to register the `ISerializationSurrogateProvider`.  At this point a `MethodNotFound` exception is thrown.  Additionally, if you are a developer, you will need to ensure you have the 4.7.1 developer pack installed in order to compile the `ExtendedXmlSerializer` project:
https://www.microsoft.com/en-us/download/details.aspx?id=56119

Looks like 4.7.1 is already installed and working in CD/CI so everything is OK there. 👍 @wojtpl2 please let me know if you have any problems with this!

**Comment by Mike-EEE** [comment]
Just a heads up here @AQuentin2033... we had some problems with this issue to get .NET 4.5 support (#160) into our NuGets.  We've introduced a new project (`ExtendedXmlSerializer.Integration`) that contains the functionality here but it does not have a NuGet package just yet.  Once we have that added you'll be able to check this out.

**Comment by Mike-EEE** [comment]
Great!  Glad to hear that.  I am taking care of that curveball right now and should have a new build that takes care of this soon.

**Comment by Mike-EEE** [comment]
Closing this issue as it has been deployed in 2.1.0:
https://github.com/wojtpl2/ExtendedXmlSerializer/issues/162

Please feel free to open an issue if you encounter any further problems.
