### ISSUE TITLE
Serialization Exception in UWP

### ISSUE THREAD

**Issue by SuperJMN** [wojtpl2/ExtendedXmlSerializer#167]
Hello! I'm here to create a new separated issue because it still fails:

As you may remember, I created the simple project for you to see it failing. I don't really know if it's completely related to EXS or with EXS + UWP or just UWP, but it's failing in the simplest scenario and it's driving me crazy. Could you, please, take a look? Thanks!

Clone this: https://github.com/SuperJMN/RtfIssue

## Steps to reproduce:

1. Build+run+deploy (deploy in either x86 or x64, AnyCPU won't work)
2. Write some text inside the box. It's a class derived from `RichEditBox `I had to create, because the original doesn't offer a **bindable** `Text `property.
3. Click on the **Save** button. 

**It can happen 2 things:** 

1. An exception is thrown
2. The file is written, **but in a corrupted state**. Check the resulting XML in the file to see the problem if the exception wasn't thrown.

I'm now sure that it's a problem with EXS because **if you use the official `XmlSerializer`, it writes the XML file just right.**

If you need any further information, please tell me!

**Comment by Mike-EEE** [comment]
Boo... that sucks as I did try this on your UWP app and it worked just fine.  I wonder what it could be.  I will look into this now.

**Comment by Mike-EEE** [comment]
So, despite my copying the text from UWP I cannot reproduce this bug in tests, unfortunately.  I was able to reproduce it from the UWP application.  It does appear that `0x00` is a character that ends the file, which is why you see the text run out.  [In this answer](https://stackoverflow.com/a/8170810/3602057) the suggestion is to use base64 characters, which can be achieve by calling our `Encrypt` method on the member currently.  I will think of how else we can tackle this.

**Comment by Mike-EEE** [comment]
OK!  I have a new extension method for you, @SuperJMN ... try using `WithValidCharacters` after the `Verbatim` call.  This will apply an alteration on that member.  You can also use this on the container and it will apply it on every `string` it encounters.  This basically strips out all invalid characters leaving only valid XML characters in the string.

You can try the latest here:
https://www.myget.org/F/wojtpl2/api/v3/index.json

**Comment by SuperJMN** [comment]
WOW WOW WOW!!    WOOORRKS!! You're the man!
🥇

**Comment by Mike-EEE** [comment]
Woohoo!  Glad something works.  Somewhere. 😄

**Comment by SuperJMN** [comment]
Hey @Mike-EEE! It seems that these changes haven't made to the NuGet package yet. I've installed the package from both NuGet.org and this feed (https://www.myget.org/F/wojtpl2/api/v3/index.json), and the GetValidCharacters method is missing:

![image](https://user-images.githubusercontent.com/3109851/39128843-28cb22d2-4709-11e8-940e-791b08405beb.png)

**Comment by wojtpl2** [comment]
I've released version 2.1.3 on Myget. 
https://www.myget.org/feed/wojtpl2/package/nuget/ExtendedXmlSerializer/2.1.3
Can you check now?

**Comment by SuperJMN** [comment]
Working now! Thank you @wojtpl2 !

**Comment by Mike-EEE** [comment]
I have noticed that there is a caching issue with versions.  You may have to clear out your `.nuget/packages` folder (or just the EXS directories) and try it that way.  I think it's because of the way our preview feed has a version, and then with how the version that is downloaded from the official nuget feed.  We might look into decorating our preview feed with `-preview` or some such nomenclature to mitigate this.
