### ISSUE TITLE
Namespaces in nullable nodes

### ISSUE THREAD

**Issue by pvlgk** [wojtpl2/ExtendedXmlSerializer#169]
Test code:

            var config = new ConfigurationContainer().EnableImplicitTyping(typeof(Book));
            config.Emit(EmitBehaviors.Always);
            var serializer = config.Create();
            Book book = new Book()
            {
                Author = "Jack London",
                Title = "The Call of the Wild",
                ISBN = null
            };

            var contents = serializer.Serialize(new XmlWriterSettings { Indent = true,  }, book);

This creates:

```
 <?xml version="1.0" encoding="UTF-8"?>
<Book>
<Author>Jack London</Author>
<ISBN xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<Title>The Call of the Wild</Title>
</Book>
```

But I want to have:

```
 <?xml version="1.0" encoding="UTF-8"?>
<Book>
<Author>Jack London</Author>
<ISBN nil="true"/>
<Title>The Call of the Wild</Title>
</Book>
```

Kind regards,

**Comment by Mike-EEE** [comment]
Cool @pvlgk thank you for sharing.  If I am not mistaken, that would make `nil` within the namespace of the default namespace, which is undefined in the document.  As I understand it, `http://www.w3.org/2001/XMLSchema-instance` must be declared as a namespace within the document element order so that its attributes can be recognized as such when being read in by a supporting serializer.  I would be interested in hearing if I have this wrong.  Also, if you are looking to make it prettier, you can use [`UseOptimizedNamespaces`](http://extendedxmlserializer.readthedocs.io/en/latest/get-started/index.html#optimized-namespaces) and it will put the `xsi` namespace at the root element.  Or at least it should. 😄

**Comment by pvlgk** [comment]
Understood. Another question. Is it possible to control  which attribute is serialized and which is not?
In a standard solution, I achieve this with the help of propert  ShouldSerialize...
        public int? NoOfPages { get; set; }

        public bool ShouldSerializeNoOfPages
        {
            get
            {
                return NoOfPages.HasValue;
            }
        }

**Comment by Mike-EEE** [comment]
You can make use of the `EmitWhen` call, which keeps your POCO plain by keeping attributes out of the picture. 😆 

```
new ConfigurationContainer().Type<Class>().Member(x => NoOfPages).EmitWhen(x => x.NoOfPages.HasValue).Create();
```

Should do the trick for you... let me know if you run into any problems @pvlgk!

**Comment by Mike-EEE** [comment]
Alright, sounds like we got this issue solved for you.  Please feel free to comment if you have any additional questions and we'll re-open it for you. 👍
