### ISSUE TITLE
Xml Deserialization Error

### ISSUE THREAD

**Issue by umutesen** [wojtpl2/ExtendedXmlSerializer#175]
I am getting this error when deserializing an XML string with version 2.1.2:

An attempt was made to load a type with the fully qualified name of 'http://namespace/file.xsd:myMessage', but no type could be located with that name.

XML:

```
<?xml version="1.0"?>
<myMessage xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://namespace/file.xsd">
  <myElement uniqueId="12345"> 
</myMessage>
```
Class:

    // <remarks />
    [Serializable]
    [XmlType(AnonymousType = true, Namespace = "http://namespace/file.xsd")]
    [XmlRoot("myMessage", Namespace = "http://namespace/file.xsd",
        IsNullable = false)]
    public class MyMessage
    {
        /// <remarks />
        [XmlElement("myElement")]
        public MyElementType MyElement { get; set; }
    }
Call to the serializer:

`_xmlSerializer.Deserialize<MyMessage>(xml)`

Possibly related to  #99

**Comment by Mike-EEE** [comment]
Ahhh that's a good point.  In v1.x we supported `XmlRootAttribute` but only in name, not the namespace.  This should be easy enough to fix.  Thank you for reporting it.  Would it be possible to get `MyElementType`'s definition just to be sure?

**Comment by umutesen** [comment]
Thank you for your response. Here is `MyElementType` class:

    /// <remarks />
    [XmlType(Namespace = "http://namespace/file.xsd")]
    public class MyElementType
    { 
        /// <remarks />
        [XmlAttribute("uniqueId")]
        public string UniqueId { get; set; } 
    }

**Comment by umutesen** [comment]
It would be quite helpful to indicate which `XML` attributes are supported in the documentation 😃

**Comment by Mike-EEE** [comment]
hah!  Well TBH our focus has been mostly on object graph serialization in the XML format, rather than being XML-standards compliant or sticking strictly to the specification.  We do certainly strive for sticking to the specification but we're aiming to breathe new life into XML while also supporting legacy scenarios within reason.  There are items such as #159 that no longer seem applicable.  Mostly in my case I just wanted an XML serializer that will serialize .NET objects no questions asked.  There were a lot of questions that had to be answered to get to that point though. 😉 

But yes, metadata-support for name/space resolution is certainly a reasonable expectation.  We had it working somewhat but it wasn't being used for namespaces.  Now it is though. 😎   Please check out the latest and see how it treats you.

**Comment by Mike-EEE** [comment]
Alright, got the list of attributes updated in our readme.  You can check them out at the repo root.
https://github.com/wojtpl2/ExtendedXmlSerializer

**Comment by umutesen** [comment]
Thank you for your prompt reply. I think you have been very successful in your aim to breathe new life into XML by supporting interface type serialization - you saved me a lot of hassle! 😄 

Is the latest version available on the myget feed? 

I tried cloning the repo and referencing a release build on my local machine but I am getting the following error in my project:

`The located assembly's manifest definition does not match the assembly reference`

FYI, I am using .net core 2.0 and registering the dependency as a transient service in `Startup.cs`.

**Comment by Mike-EEE** [comment]
Indeed, our CI/CD kicks in and the MyGet feed gets updated with each commit... for better or for worse. 😆 

> The located assembly's manifest definition does not match the assembly reference

Hmm... strange... does it say which assembly it's having this issue?

**Comment by Mike-EEE** [comment]
You could also try adding the .csproj to your SLN and see if that mitigates it as well.

**Comment by umutesen** [comment]
Here is the stack trace from the exception I got when referencing the dll:

```
System.IO.FileLoadException: Could not load file or assembly 'ExtendedXmlSerializer, Version=2.1.2.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'ExtendedXmlSerializer, Version=2.1.2.0, Culture=neutral, PublicKeyToken=null'
   at NG.ERS.API.Startup.ConfigureServices(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```

I added the .csproj file to the solution and it fixed the above issue but I would like to use the nuget package from myget feed. I did not see an update in the nuget package manager even though the published date was today. I removed the package and installed it again but I am still getting the original exception:
`An attempt was made to load a type with the fully qualified name of...`

Just to confirm, there is no configuration required with regards to enabling deserialization, is there? This is how I am setting up the serializer:

```
            services.AddTransient<IExtendedXmlSerializer>(provider =>
            {   
                var serializer = new ConfigurationContainer()
                    .EnableReferences()
                    .EnableAllConstructors()
                    .Create(); 
                return serializer;
            });
```
It seems like the serializer is using the namespace and the name of the root node in XML, which is expected behaviour IMO but it is not recognising the namespace definition in the class.

**Comment by Mike-EEE** [comment]
OK cool.  The suggestion to add the csproj was to eliminate possible factors.  I am actually not too familiar with ASP.NET Core, but everything should "just work" without any issues.

Obviously there is a reference issue.  I hate these. 😉  I am assuming you have cleared all your caches/solution/bin/obj folders and have done a "Clean -> Rebuild"?

 @wojtpl2 might be able to provide additional suggestions here as he has done some work around AspNet.Core.

**Comment by umutesen** [comment]
I just created a new unit test project, got the latest version from MyGet and created the following test to isolate the issue, 

```
    [TestClass]
    public class DeserializationTests
    {

        private IExtendedXmlSerializer _xmlSerializer;

        [TestInitialize]
        public void TestInitialise()
        {
            _xmlSerializer = new ConfigurationContainer().Create();
        }

        [TestMethod]
        public void Deserialize_WithNamespace_CreatesMessage()
        {
            var xml = @"<?xml version=""1.0""?>
                        <myMessage xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns=""http://namespace/file.xsd"">
                            <myElement uniqueId=""12345""> 
                        </myMessage>";

            var msg = _xmlSerializer.Deserialize<MyMessage>(xml);

            Assert.AreEqual(msg.MyElement.UniqueId, "12345");
        }
    }
      

    [Serializable]
    [XmlType(AnonymousType = true, Namespace = "http://namespace/file.xsd")]
    [XmlRoot("myMessage", Namespace = "http://namespace/file.xsd", IsNullable = false)]
    public class MyMessage
    {
        /// <remarks />
        [XmlElement("myElement")]
        public MyElementType MyElement { get; set; }
    }

    /// <remarks />
    [XmlType(Namespace = "http://namespace/file.xsd")]
    public class MyElementType
    {
        /// <remarks />
        [XmlAttribute("uniqueId")]
        public string UniqueId { get; set; }
    }
```


Test result:

```
Test method NG.ERS.API.UTests.DeserializationTests.Deserialize_WithNamespace_CreatesMessage threw exception: 
System.InvalidOperationException: An attempt was made to load a type with the fully qualified name of 'http://namespace/file.xsd:myMessage', but no type could be located with that name.
    at ExtendedXmlSerializer.ContentModel.Extensions.GetClassification(IClassification this, IFormatReader parameter, TypeInfo defaultValue)
   at ExtendedXmlSerializer.Read`1.Get(T parameter)
   at ExtendedXmlSerializer.ExtensionModel.Xml.Extensions.Deserialize[T](IExtendedXmlSerializer this, IXmlReaderFactory factory, Stream stream)
   at NG.ERS.API.UTests.DeserializationTests.Deserialize_WithNamespace_CreatesMessage() in D:\Source\\src\NG.ERS\NG.ERS.API.UTests\DeserializationTests.cs:line 31
```

**Comment by Mike-EEE** [comment]
Boh!  Yeah that's a minor detail isn't it. 😛 ... We're still emitting clr-namespaces.  Actually my "fix" didn't a darn thing except make sure it reads metadata haha.  I will look into this.  We'll have to use some sort of type registration mechanism but in the case where you specify the type explicitly during deserialization we'll hook into that and get the type(s) from there.

**Comment by umutesen** [comment]
I should've supplied that test from the start, sorry about that 😄 

I removed all namespaces and it still seems to throw the issue
```

    [TestClass]
    public class DeserializationTests
    {

        private IExtendedXmlSerializer _xmlSerializer;

        [TestInitialize]
        public void TestInitialise()
        {
            _xmlSerializer = new ConfigurationContainer().Create();
        }

        [TestMethod]
        public void Deserialize_WithNamespace_CreatesMessage()
        {
            var xml = @"<?xml version=""1.0""?>
                        <myMessage>
                            <myElement uniqueId=""12345""> 
                        </myMessage>";

            var msg = _xmlSerializer.Deserialize<MyMessage>(xml);

            Assert.AreEqual(msg.MyElement.UniqueId, "12345");
        }
    }

    public class MyMessage
    {
        [XmlElement("myElement")]
        public MyElementType MyElement { get; set; }
    }

    public class MyElementType
    {
        [XmlAttribute("uniqueId")]
        public string UniqueId { get; set; }
    }

```

`System.InvalidOperationException: An attempt was made to load a type with the fully qualified name of 'myMessage', but no type could be located with that name.`

Is this expected behavior?

**Comment by Mike-EEE** [comment]
Actually you did provide the test earlier, I just didn't use it. 👼  ... but the problem here is identity resolution, obviously.  It might help to make use of the `Serialize` method to see how it is emitted, first.  CLR types are emitted with a Xaml-esque namespace attribute unless their assembly is registered as a root identity (e.g `sys` or `exs`).  So we do a good job (now) of accounting for names, but namespaces are not registered (nor checked).  The good news is that it's mostly in place to do so and I should have something shortly here for you to test.  Again. 😆

**Comment by Mike-EEE** [comment]
OK @umutesen I think I finally have something for you... FOR REALZ THIS TIME.  😆  The only consideration now is that you have to include a call to `InspectingType<T>` where `T` is the root type of your model.  It will traverse the entire graph and collect all referenced types from the property types.  Additionally, if for some reason it doesn't catch the type you are looking for, there is a `InspectingTypes` call where you can pass in a set of types, and again will enumerate through their graphs and get them registered.  I've got your test passing now.  However, do note there is no closing `/>` in your `myElement ` tag above so that was throwing an error.  Adding this passes the test.  Please let me know if you run into any additional problems.

**Comment by umutesen** [comment]
Hi, thank you for the update 👍 Just checked myget and the version number is still the same. I reinstalled it but I am not getting the `InspectingType<T>` option. Am I missing something?

**Comment by wojtpl2** [comment]
We can publish new version 2.1.2. @Mike-EEE What do you think? Can you provide me release node?

**Comment by Mike-EEE** [comment]
For sure @wojtpl2 ... looks like d4d99cc633217f473a9e32e0fb7042892f6369f3 is the winner here. 👍

**Comment by wojtpl2** [comment]
I've just published version 2.1.2.

**Comment by Mike-EEE** [comment]
Woohoo, great.  Thank you @wojtpl2!  I have updated #162 with all of the new issues/features as well.  Closing this issue for now.  Please feel free to comment if this issue persists in any way, or feel free to open a new issue altogether if you feel that is appropriate.

**Comment by rbigbie** [comment]
I must be doing something wrong, because I am not sure what I need to do to consume the fix as stated above. I receive the same message "An attempt was made to load a type with the fully qualified name of 'Foo', but no type could be located with that name." I read through this thread, but in this thread it is not explained on how to use `InspectingType<T>().` And I do not see it in the documentation.  I added `var serializer = new ConfigurationContainer().InspectingType<Foo>().Create();
var foo= serializer.Deserialize<Foo>(xml);` to my code and upon a rebuild I received the same message. I am using version 2.1.3. My class definition which is in another reference project within my solution is decorated as the following: `[Serializable]
    [XmlType(AnonymousType = true, Namespace = "http://namespace/file.xsd")]
    [XmlRoot(ElementName = "Foo", IsNullable = false)]
    public class Foo: IFoo
    { // left out the meat due to public post }`. I feel like an idiot because I feel like I am missing something.  Any ideas?

**Comment by Mike-EEE** [comment]
Hi @rbigbie thanks for checking in and sorry about the documentation.  Unfortunately this issue is what we have right now, and the documentation "lives" in the unit test which you can find here:

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue175Tests.cs

(Basically when a new issue is reported, it gets its own testing class with working code/test)

From eyeballing it, I think the problem might be the `XmlRoot` which needs a `Namespace` attribute assigned to it.  Try adding that and see if that helps you out.  If you continue to run into a problem I will be more than happy to help out and get you situation. 👍

**Comment by Mike-EEE** [comment]
So... _finally_ adding documentation here and encountered the `InspectingType` method just now and landed on this thread.  I re-read your comment @rbigbie and realized that indeed there was an oversight in how identities are resolved with this method.  Essentially, there can be a "cross-over" scenario where one attribute has the namespace and another attribute has the namespace (or vice versa).

I have added a commit to this that addresses a scenario, complete with passing test which is defined here:

https://github.com/ExtendedXmlSerializer/ExtendedXmlSerializer/blob/93fdfa95eb5fb529cef3b5da967c936a365344ef/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue175Tests.cs#L60-L84

If interested, you can use our new preview feed here to check it out:

https://ci.appveyor.com/nuget/extendedxmlserializer-preview

Please be sure to select Browse and enable `Include prerelease` in NuGet explorer:

![](https://i.imgur.com/lpZeYIy.png)
