### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dbeattie71** [wojtpl2/ExtendedXmlSerializer#186]
Is it possible to implement a solution similar to: [155](https://github.com/wojtpl2/ExtendedXmlSerializer/issues/155#issuecomment-360807673) without using XmlElementAttribute?  I know 155 has the choice attribute but in my case I haven't been using that.  I've just decorated the property with XmlElementAttribute and the possible types the property can be.

I've looked at Issue 180 also trying to understand how Extensions work.  In that example I was trying to understand how a custom serializer is implemented for one property.

I made up a failing test, can exs namespace be eliminated?  I realize that will mess up deserialization but in this case that's ok.
https://gist.github.com/dbeattie71/2b1bf92d90ecbe49f635a8906b34fcba

**Comment by Mike-EEE** [comment]
Hi @dbeattie71 thanks for writing in and asking about this.

I am trying to better understand what you are facing here.  Are you concerned about the extra namespace attribute(s) -- `exs` in this case?

Also, it would be valuable to know if you have encountered a scenario where the default serialization did not work and/or what you do not like about the current serialization result.  That is, if it's more than just the extra namespace attributes.

Currently in v2 we cannot do away with the exs namespace (not without a lot of work that is -- but PRs are welcome 😄), but for v3 this is certainly something we can keep in mind when/while we're designing it.  

When it comes to namespaces we are using the underlying classic `System.Xml.XmlReader` and System.Xml.XmlWriter` infrastructure that helps resolve these namespaces and properly resolve these entities.  These of course are based on the XML standard/specification and help keep attributes properly identified and separated from their hosting elements.  

For v3 we're looking at writing our own implementation of such concerns, so we will be able to be much more flexible in how we read/write objects and their respective properties.

**Comment by Mike-EEE** [comment]
So I want to walk you through your serialization, @dbeattie71 as I am interested in this topic as of late.

As above, you have this as (with the quotes corrected for XML syntax compliance):

```
<?xml version="1.0" encoding="utf-8"?>
<SubjectRequest>
	<Subject2>
		<Message>message1</Message>
		<Message2>message2</Message2>
	</Subject2>
</SubjectRequest>
```

The first thing to note is that there is no `SubjectRequest.SomeInterface` property.  So you would need to specify it as such:

```
<?xml version="1.0" encoding="utf-8"?>
<SubjectRequest>
	<SomeInterface>
		<Subject2>
			<Message>message1</Message>
			<Message2>message2</Message2>
		</Subject2>
	</SomeInterface>
</SubjectRequest>
```

Conceivably, we could now use the implicit types to serialize the remaining `Subject2` tag.  Since implicit types are keyed by the name, we could find the one that exists at this name and then try to deserialize it.

The reason I am interested in this is due to my recent research into TOML/YAML "configurations" in Jekyll and Hugo.  Everything is very "clean" these days without much decoration.  I understand the appeal of this, which is why we have implicit typing in the first place.  However in this case we still spill out namespaces because the type could be anything.  Let me see if we can simply dispatch a lookup to implicit types and re-reroute the processing through there.

**Comment by dbeattie71** [comment]
The `exs` isn't a big deal as I have some code that removes namespaces.  Adapted from [https://github.com/BizTalkComponents/ManageMessageNamespace](url).  The docs for the request I'm building are here [http://www.byallaccounts.net/manuals/dataconnect/dataconnect_v4_ultra_user_guide.pdf](url).  For some reason if the request is sent with any namespace info, it gets rejected.  Possibly because they add they're own.

This [https://gist.github.com/dbeattie71/8efae93d7e1e5d31df0de6dea671256a](url) is a snippet of whats created when converting their DTD to XSD and then using xsd.exe.  I'm trying to emulate what happens when the `Item` property is an object and decorated with `XmlElementAttribute`.

I'm guessing that what xsd.exe creates should be like #155 and have a `XmlChoiceIdentifierAttribute` but some things in DTD probably don't exactly map to XSD.

So what I'm after is being able to create `SubjectRequest` and set `SubjectRequest.SomeInterface` to any type that implements it and when `SubjectRequest` is serialized, have the element name of the type that implemented `ISomeInterface`.

Chances are I'm making this more difficult than it is but I was also trying to understand how extensions work as they seem really flexible and thought I could just make an extension that for a certain property, spit out a different element name.

Somewhat off topic but you might be interested in [https://github.com/Cinchoo/ChoETL](url)

For Extensions, I've been basically trying to understand the anatomy of an extension.  Looking at Issue180 and all the other extensions.

**Comment by Mike-EEE** [comment]
Ah OK cool thank you for those links and for the pointer to ChoETL.  I'll check it out. 😄 

I think I see now what you're driving at.  I have checked in an example here:
https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue186Tests.cs

You could possibly simply set the name.  However, that is a static name and there isn't at present a way to dynamically set the name during runtime.  But, conceivably you could create a new serializer for each request and set the name as prescribed.  Let me know if that is closer to what you are looking to do.

The other option as well if you have not considered it is to use XSLT.  You should be able to easily set the name of the property name with that as well.

**Comment by dbeattie71** [comment]
Thanks, that makes sense.  I didn't think about xslt, that may be more flexible.  I've also seen people set an ignored property to what they want the element name to be and then use `XmlAttirubteOverrides` to set the ElementName to the property.  I might play with that and extensions and see what I can come up with.

**Comment by Mike-EEE** [comment]
Yeah for sure.  Sorry I can't be much more help ATM.  The v2 codebase is pretty much set in stone until v3 unless it's a pretty obvious feature that can be handled by an extension.  In this case we're sort of tied up because of the attributes and namespacing.  Please do let us know what you find.  FWIW we do not make use `XmlAttributeOverrides` in our current implementation but _most_ attributes do have support.  Please let me know if you have any further questions and I'll do my best to help you... hopefully better than I have thus far. 👼

**Comment by dbeattie71** [comment]
No problem, thanks.  I enjoy looking through the code and figuring out how things work.

**Comment by Mike-EEE** [comment]
Closing this issue for now.  Please do not hesitate to add a new issue or to comment here if you have further thoughts/questions/concerns about this issue/project. :)
