### ISSUE TITLE
Documentation: Further explain how EnableReferences() works

### ISSUE THREAD

**Issue by FaustoNascimento** [wojtpl2/ExtendedXmlSerializer#202]
There's a small section in the readme about how `EnableReferences()` works, but the sole example shows the usage of an `Id` property at the class level but at the same time there's an overload for `EnableReferences()` that accepts no parameters.

I *would expect* that when the overload with no parameters is called that `ExtendedXmlSerializer` automatically creates an internal ID for the object, but this isn't clear from the documentation.

Also, what's the difference between `EnableReferences()` and `EnableDeferredReferences()`?

Also, when using multiple extensions, in which order do they apply?

**Comment by Mike-EEE** [comment]
Heya @FaustoNascimento thank you for writing in.  Indeed we have a bit of a documentation deficiency here.  Our repo here with issues has been picking up the slack as we get developers asking questions, so I have tried to assist with filling out the blanks as they occur.  I myself hate writing documentation but enjoy typing to an actual human being (wait, you are real, right? 😆) so we get what we get.

ANYWAYS, your expectations are indeed aligned with reality.  Typically in a serializer you will see a reference handling "mode" or an enum that specifies what happens when a circular dependency is encountered.  By default we throw an exception.  If you want to instead enable it to serialize the graph, `EnableReferences` is provided for you.  Here again your expectations are correct: ExtendedXmlSerializer will create a unique ID for each reference it encounters and emit it with a special attribute.

Given the following class:

```
public class Subject
{
	public string Name { get; set; }
	public Subject Subject1 { get; set; }
}
```

And code:
```
var subject = new Subject();
subject.Subject1 = subject;
new ConfigurationContainer().EnableReferences().Create().Serialize(subject);
```

We will produce the following XML:

```
<?xml version="1.0" encoding="utf-8"?><Issue202Tests-Subject xmlns:exs="https://extendedxmlserializer.github.io/v2" exs:identity="1" xmlns="clr-namespace:ExtendedXmlSerializer.Tests.ReportedIssues;assembly=ExtendedXmlSerializer.Tests">
    <Subject1 exs:reference="1" />
</Issue202Tests-Subject>
```

The `exs:identity` is the id of the reference as it occurs in the graph first.  For subsequent appearances `exs:reference` is used to denote it.

The other aspect of references has to do with declared identity fields.  Here you tell ExtendedXmlSerializer which field in a type is the identity.

So the following code:
```
var subject = new Subject {Name = "My name, yo."};
subject.Subject1 = subject;
new ConfigurationContainer().Type<Subject>().EnableReferences(x => x.Name).Create().Serialize(subject);
```

Will produce the following Xml:

```
<?xml version="1.0" encoding="utf-8"?><Issue202Tests-Subject Name="My name, yo." xmlns="clr-namespace:ExtendedXmlSerializer.Tests.ReportedIssues;assembly=ExtendedXmlSerializer.Tests">
    <Subject1 xmlns:exs="https://extendedxmlserializer.github.io/v2" exs:entity="My name, yo." /></Issue202Tests-Subject>
```

You can see that the `Name` property is used as the identity field (no special attribute required), and we also use the `exs:entity` to point to the source reference.

Now, `EnableDeferredReferences` is a bit trickier and has to do with how references are emitted.  In all honesty we could have called this one `EnableReferencesLikeV1Did` because that is what @wojtpl2 wanted. 🤣  I preferred having the first identified reference in the graph be the primary one, whereas v1 had a different way of doing it.  Essentially in this case references that are an element in a list take precedence over those that are not.  The case could be made (and it was 👼) that deferring the reference capture looks better in emitted document composition than a graph without it.

To give you an example, here is a graph with `EnableReferences`:

```
<?xml version="1.0" encoding="utf-8"?>
<TestClassReferenceWithList xmlns="clr-namespace:ExtendedXmlSerializer.Tests.TestObject;assembly=ExtendedXmlSerializer.Tests">
	<Parent xmlns:exs="https://extendedxmlserializer.github.io/v2" exs:type="TestClassReference" Id="1" />
	<All>
		<Capacity>4</Capacity>
		<TestClassReference Id="3">
			<ObjectA xmlns:exs="https://extendedxmlserializer.github.io/v2" exs:type="TestClassReference" exs:entity="1" />
			<ReferenceToObjectA xmlns:exs="https://extendedxmlserializer.github.io/v2" exs:type="TestClassReference" exs:entity="1" />
		</TestClassReference>
		<TestClassReference Id="4">
			<ObjectA xmlns:exs="https://extendedxmlserializer.github.io/v2" exs:type="TestClassReference" Id="2">
				<ObjectA exs:type="TestClassReference" exs:entity="1" />
				<ReferenceToObjectA exs:type="TestClassReference" exs:entity="1" />
			</ObjectA>
			<ReferenceToObjectA xmlns:exs="https://extendedxmlserializer.github.io/v2" exs:type="TestClassReference" exs:entity="2" />
		</TestClassReference>
		<TestClassReference xmlns:exs="https://extendedxmlserializer.github.io/v2" exs:entity="2" />
		<TestClassReference xmlns:exs="https://extendedxmlserializer.github.io/v2" exs:entity="1" />
	</All>
</TestClassReferenceWithList>
```

And here is the same document with `EnableDeferredReferences`:

```
<?xml version="1.0" encoding="utf-8"?>
<TestClassReferenceWithList xmlns="clr-namespace:ExtendedXmlSerializer.Tests.TestObject;assembly=ExtendedXmlSerializer.Tests">
	<Parent xmlns:exs="https://extendedxmlserializer.github.io/v2" exs:type="TestClassReference" Id="1" />
	<All>
		<Capacity>4</Capacity>
		<TestClassReference Id="3">
			<ObjectA xmlns:exs="https://extendedxmlserializer.github.io/v2" exs:type="TestClassReference" exs:entity="1" />
			<ReferenceToObjectA xmlns:exs="https://extendedxmlserializer.github.io/v2" exs:type="TestClassReference" exs:entity="1" />
		</TestClassReference>
		<TestClassReference Id="4">
			<ObjectA xmlns:exs="https://extendedxmlserializer.github.io/v2" exs:type="TestClassReference" exs:entity="2" />
			<ReferenceToObjectA xmlns:exs="https://extendedxmlserializer.github.io/v2" exs:type="TestClassReference" exs:entity="2" />
		</TestClassReference>
		<TestClassReference Id="2">
			<ObjectA xmlns:exs="https://extendedxmlserializer.github.io/v2" exs:type="TestClassReference" exs:entity="1" />
			<ReferenceToObjectA xmlns:exs="https://extendedxmlserializer.github.io/v2" exs:type="TestClassReference" exs:entity="1" />
		</TestClassReference>
		<TestClassReference xmlns:exs="https://extendedxmlserializer.github.io/v2" exs:entity="1" />
	</All>
</TestClassReferenceWithList>
```

You can see that in the deferred document, entity `2` is encountered first in the graph (as a property), but its identity is deferred until the element is emitted later on.  Hope that makes sense.  Please let me know if you have any further questions around this and I will do my best to answer.

FINALLY... as for multiple extensions, yes indeed, they are added in the order which they are encountered.  For v3 we have a dependency story around this so that if you add an extension and it is dependent on another, it will order itself accordingly.

**Comment by FaustoNascimento** [comment]
If you find some time, adding some more stuff to the readme about circular dependencies would be great, other than that pretty happy with the explanation given and the issue can be closed.

**Comment by Mike-EEE** [comment]
YOU HAVE INSPIRED ME @FaustoNascimento !!! 😆

Check it out:
https://github.com/wojtpl2/ExtendedXmlSerializer/wiki/How-Circular-References-Are-Handled

Closing for now.  Please feel free to continue here with any additional comments.
