### ISSUE TITLE
Is ExtendedXmlSerializer thread safe?

### ISSUE THREAD

**Issue by bpaczkowski** [wojtpl2/ExtendedXmlSerializer#208]
I have a single static instance of IExtendedXmlSerializer defined like so: `new ConfigurationContainer().Create()`. It is used in multiple threads. I haven't had any problems with it, but I wanted to make sure that this is the intended and safe way to use it, can someone confirm or deny this? I don't see it mentioned in the docs and readme, I only found one vague issue comment [here](https://github.com/wojtpl2/ExtendedXmlSerializer/issues/10#issuecomment-263581109).

**Comment by Mike-EEE** [comment]
It *should* be. :)  Your profile picture is perfect for my assessment, @bpaczkowski. 😆

FWIW I had a problem once with initialization so I added an `EnableThreadProtection` extension method (and extension, of course).  Here it is in action:

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/afe70bb87188072c94b31f3f0151991faabf9d59/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue208Tests.cs#L17-L30

That *should* take care of any issues you might encounter.  Please note that this accounts for the components within ExtendedXmlSerializer and you will have to manage external components (such as streams) on your own.

Please let me know if you encounter any issues around this and I will look further into it for you.

**Comment by bpaczkowski** [comment]
But theoretically `EnableThreadProtection` is not needed? I think locking the serializer would result in a performance degradation.

From my testing it would seem that ExtendedXmlSerializer stores some state internally even between instances of ExtendedXmlSerializer, is that correct? The way I tested is the first parsing of an xml after starting a process is the longest, all further parsing is an order of magnitude faster, even when recreating the serializator.

**Comment by Mike-EEE** [comment]
> I think locking the serializer would result in a performance degradation.

It _totally_ does!  Haha.  I do not think it is needed except for some scenarios where you might have a race condition with creating a serializer.  Technically that is not the concern of EXS and could be handled outside of it.  It's probably why I haven't really mentioned it until now, either.  

And yes there is a lot of caching mechanisms that are employed so that sounds about accurate.  Most are via static singletons which are probably being accessed for the first time which is the startup cost that you are experiencing.  It shouldn't be too bad though.  We are right up there in terms of speed with the classic serializer.  Or were.  I had a little issue with the performance story and got a little derailed. ([Long story](https://blog.superdotnet.run/2018/05/investigating-weird-result-times-in-benchmark-net/) haha).

If any issues do arise or something seems awry please do bring it to our attention and we'll check it out.

Also:
![2ifztk](https://user-images.githubusercontent.com/2931376/45894429-50073e80-bd9c-11e8-855f-5c3b264c5a0d.jpg)

😂

**Comment by bpaczkowski** [comment]
Ahh I see. The serializer is created statically so I guess that shouldn't be a problem. Thanks for the prompt response.

That "long story" was an interesting read :wink:

I do have another totally unrelated question. Is the big performance degradation when using `UseOptimizedNamespaces` expected? Not a very good example, but recently we had a migration that required parsing and serializing back a few hundred xmls, some of them relatively big (still under 1 MB though). When `UseOptimizedNamespaces` was used, that migration took over an hour. With it removed and nothing else changed, the time needed was reduced to mere seconds. Reproducible every time. I could look into this a little more and maybe come up with a small repro project, but I wanted to make sure it's not the expected behavior.

**Comment by Mike-EEE** [comment]
> That "long story" was an interesting read 😉

Haha I honestly am so burnt out over that whole ordeal.  I had about 10% of the energy required to even force myself to write anything remotely close to it.  It's cool now as I have a much better perspective when diving into performance and have the tooling needed to weed out false positives, etc.  But still.  THE BURN OMG NEW TOPIC PLEASE.

> When UseOptimizedNamespaces was used, that migration took over an hour. With it removed and nothing else changed, the time needed was reduced to mere seconds.

WOW... that does sound suspicious.  To be certain we do travel the object graph each time to ensure we have all the necessary namespaces but that sounds _overwhelmingly_ inordinate!  I will look into this one and see what I can find.  Is there any chance you can provide the class(es) used in your migration?  There might be something funky going on with the graph that we haven't considered.  Obfuscating the names is OK if it's a data issue.  I am interested in the types used.

I have captured this in a new issue here:
https://github.com/wojtpl2/ExtendedXmlSerializer/issues/209

**Comment by Mike-EEE** [comment]
Closing this for now as I believe we answered the driving question here.  Please feel free to comment further and we can re-open if need be.
