### ISSUE TITLE
Ignore default value

### ISSUE THREAD

**Issue by bpaczkowski** [wojtpl2/ExtendedXmlSerializer#211]
Is this behavior configurable? When I explicitly set a property to null, but it has a default value, the serialized XML does not include that property, and when deserializing the XML that property is no longer null and now has the default value instead.

**Comment by Mike-EEE** [comment]
Indeed it is @bpaczkowski.  Check it out:

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/a22caeee46a6876120ece21aad51f6e9e821b5ed/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue211Tests.cs#L24-L30

Making use of the `EmitBehaviors` configuration.

Please let me know if you have any questions around this or anything else for that matter.  Questions like these are basically filling in the gaps for documentation until I can unlazify myself and actually write something. 😆

**Comment by Mike-EEE** [comment]
Yikes!  Yeah please let me know if you can get a simple repo and I can take a look into it. 👍

**Comment by bpaczkowski** [comment]
Something isn't right, I found 2 separate exceptions connected to `EmitBehavior.Assigned` (they don't occur with the default behavior):

- When `.EnableReferences()` is used, even the simplest class throws an exception. I tried the one from the test above and it threw an exception.
- Serializing this class also throws an exception, but different to the one mentioned above, and it throws even without EnableReferences:
	```
	public class Foo
	{
		public DateTime? Date { get; set; } = DateTime.MinValue;
	}
	```

**Comment by Mike-EEE** [comment]
Alrighty, thank you for reporting these, @bpaczkowski.  I believe I have addressed the issue.  This is one of those murky areas where we have overlap between extensions and expected behavior in the default components.  Essentially, the philosophy has been to relegate the decision-making to the `IMemberConfiguration` (per member) whether something can be emitted.  This works fine until you get into null-land as you have bravely wandered into. 😁

Same goes for our references extension.  A few assumptions were made with the instance value always being assigned (non-null), as that is the only way it would get into that extension in the first place.  Different story when you change the emit behavior, of course.

These have been addressed.  You can view the fixes here in the preview feed:
https://www.myget.org/F/wojtpl2/api/v3/index.json

Please note that if you have already downloaded a package from this feed you might have to delete your existing `c:\user\.nuget\packages\ExtendedXmlSeralizer` copy due to our known issue in #184.

**Comment by bpaczkowski** [comment]
I can confirm that both issues I was experiencing are now fixed, thanks for doing it so quickly!

**Comment by Mike-EEE** [comment]
Woohoo!  That's good to hear.  Hopefully you won't experience too much more friction. 🤞  But if you do let me know and I will look into it for you. :)

I am going to see if upping the version can get a deployment out to nuget.  It didn't seem to like the last one we tried, but that might have been due to the tag already existing.  Here goes nothing. 😆

**Comment by Mike-EEE** [comment]
Bummer... it didn't take.  Hopefully, we can get it addressed soon.  I will update this thread when it is.

**Comment by bpaczkowski** [comment]
I found another issue. Not sure if it belongs in a new issue or not, you can decide that.

When a property of abstract type is null, and EmitBehavior is Always (or the default value is other than null and EmitBehavior is Assigned) there is an exception when serializing. Example classes:

```
public class TestClass
{
	public TestClass2 TestClass2 { get; set; }
}

//     vvvvvvvv
public abstract class TestClass2
{
	public string Foo { get; set; }
}
```

May I also add that the exceptions ExtendedXmlSerializer generates are cryptic at best? Debugging these exceptions boils down to removing properties one by one and checking each time if the exception stopped appearing.

**Comment by Mike-EEE** [comment]
For sure keep feeding these issues and comments, I very much appreciate you taking the time to not only try out our project but also taking the further step when something goes wrong to report it.  Not a lot of developers do that so I would like to give you some props for doing so. 🎖🎉

Also. feel free to report them as separate issues so we can track thread/history.  I will look into the abstract class issue now (#213).

As for exception handling, I definitely concede to your angst.  When we were initially developing v2, performance was a priority/focus (until it wasn't as noted earlier 😂), so niceties like exception handling were not provided as it does incur an overhead.  HOWEVER now thinking about this, it's something an extension could take care of nicely.  I will look into getting this for you as well, @bpaczkowski. 👍

**Comment by Mike-EEE** [comment]
I believe all issues identified here have been resolved and deployed to the public nuget feed in `2.1.13`.  Please let us know if this is not the case and we can revisit this.  Thanks again for being so proactive and identifying #AllTheBroken, @bpaczkowski!
