### ISSUE TITLE
Implicit typing fails to serialize

### ISSUE THREAD

**Issue by SuperJMN** [wojtpl2/ExtendedXmlSerializer#231]
Hello!

I've created a very basic set of classes that I want to serialize.

**Problem:**
Upon calling to `Serialize`, it throws an `ArgumentException` with the following message 

`The empty string '' is not a valid name.`

I'm attaching a project with a test method that reproduces the issue. I hope you
[TestEXS.zip](https://github.com/wojtpl2/ExtendedXmlSerializer/files/2753345/TestEXS.zip)

Is it because I'm doing something wrong? I hope you can take a look. Thanks!

**Comment by Mike-EEE** [comment]
Hey @SuperJMN!  Thanks for checking in with this.  Unfortunately, I am outside of a working environment ATM (setting up a new one) so will not be able to look into this for you for the next day or so.  I'm sort of working out of a briefcase right now and it sucks. :P   Anyways, I will let you know what I find when I can. 👍

**Comment by SuperJMN** [comment]
Thanks Mike! I'm glad to spot some bugs to make EXS even better! Have you already reproduced the issue?

**Comment by Mike-EEE** [comment]
Ah no I suck, sorry about this @SuperJMN.  I am so embarrassed to admit how much time I've spent on this, not to mention that I have several other projects/issues that I am juggling right now.  I have circled a "home base" contingency plan, however, and for sure will have myself back online over the weekend.

Can you put this on a repo somewhere, by chance?  I can eyeball it from here out of a tablet. :P  I am wary of zip files and usually have a sandbox environment to handle those, when I have an environment, that is. 😅

**Comment by Mike-EEE** [comment]
OK!  The problem here is that a different kind of `XmlWriter` than what is used in the default framework is used here.

By default, EXS makes use of the `XmlWriter.Create` which has a default implementation that allows `null` to be passed into its `LookupPrefix` method.

`XmlTextWriter`, however, does a guard check on this and throws.

I have provided a way to override the implementation used to lookup prefixes to avoid this issue.

Please try out the preview feed and see if your code works now.  You shouldn't have to change anything:

https://www.myget.org/F/wojtpl2/api/v3/index.json

Let me know if you run into any problems and we can address, otherwise we can then push to NuGet. 👍
