### ISSUE TITLE
XmlTextAttribute not supported

### ISSUE THREAD

**Issue by ddrdoubled** [wojtpl2/ExtendedXmlSerializer#242]
Hi there,

is the XmlTextAttribute currenty not supported? Or is there any other kind of possibility to serialize Element Property into Text?

like:
public class IdentifiedDate {
[XmlAttribute(DataType = "ID")]
public string id {get; set;}
[XmlText(DataType = "date")]
public DateTime Value {get; set;}
}

which should serialize for a property of IdentifiedDate like:
<unadjustedDate id="Value Date">1994-12-14Z</unadjustedDate>
instead with ExtendedXmlSerializer gives:
<unadjustedDate id="Value Date">
<Value>1999-12-14T01:00:00+01:00</Value>
</unadjustedDate>

**Comment by Mike-EEE** [comment]
hey @ddrdoubled thanks for writing in here with your question.

We do support `XmlTextAttribute` but it is very brittle.  I should say that ExtendedXmlSerializer v2 was made with POCO serialization in mind from the outset, with an eye on legacy/classic serialization, but not a focus.

If you are simply interested in serializing a date property without the time, you can use a custom converter and serializer as seen here:

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/6290d692c4a88314a98df869d4ce0bf1efc273fa/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue242Tests.cs#L17-L30

However this does not make use of the inner-content which is a bit of a thorn here as referenced in #240.

In my example here this is for one property.  If you have numerous properties that need to render a date-only, we could probably do that with an extension, by looking for properties that are decorated with `[XmlText(DataType = "date")]`.

It would involve some work though so wanted to check with you first before I proceeded that route. :)

Let me know how this works for you and if I can assist any further.

**Comment by Mike-EEE** [comment]
We have not heard anything further so we will close this issue for now.  Please feel free to ask any additional questions you might have and we will be happy to re-open and discuss further.  Thanks again for writing in!

**Comment by ddrdoubled** [comment]
Hi Mike, sorry i don't get it, the XmlTextAttribute has nothing to do with DateTime, it means that the property of a parent object is serialized as a string attribute for the parent object, 
see for example:
https://stackoverflow.com/questions/6168961/how-to-deserialize-an-xml-node-with-a-value-and-an-attribute-using-asp-net-seria

**Comment by Mike-EEE** [comment]
Ahh correct, @ddrdoubled ... what I was focused on was the `DataType = "date"` which as you denoted in your original post (surprisingly)  emits a different date-time format than the default formatting.  My impression was that you were looking for a way to format the date in a particular way, so that appears to be wrong.

If what you are asking is if we support the `XmlTextAttribute` as utilized in classic serialization, then no we do not at present -- not completely, at least.  Our focus has been with POCO serialization rather than classic serialization if that makes sense.

Re-opening for now. Please feel free to leave additional comments and/or close if you feel this has been answered. 👍

**Comment by Mike-EEE** [comment]
Closing this issue for now.  Please let us know if you have any further questions around this issue or any others and we will do our best to assist.
