### ISSUE TITLE
ExcludeFromCodeCoverageAttribute conflict

### ISSUE THREAD

**Issue by bpaczkowski** [wojtpl2/ExtendedXmlSerializer#244]
This attribute is for some reason included in the library with the original namespace which causes conflicts with the real assembly which includes this attribute.

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/05adb69c4d2d32006ea013238b3b67066e12bf58/src/ExtendedXmlSerializer/Core/LightInject/LightInject.cs#L42

**Comment by Mike-EEE** [comment]
Weird!  I think this is due to moving things over to .NET Standard 2.0 back in the day and there were some compilation issues between .NET Framework and .NET Core.

In any case, I've committed a fix and is available on our preview feed:
https://www.myget.org/F/wojtpl2/api/v3/index.json

I will also kick out a version to nuget since this is the only issue we've had in a while (and I'm not complaining 😆) and will update here when it's available.  

Thanks for letting us know. 👍

**Comment by Mike-EEE** [comment]
Alrighty, `2.1.18` is available.  Please let us know if you run into any troubles.

https://www.nuget.org/packages/ExtendedXmlSerializer/

Closing for now.

**Comment by bpaczkowski** [comment]
Thanks for the quick fix as always 😃
