### ISSUE TITLE
EmitBehaviors and Empty tags and Empty strings

### ISSUE THREAD

**Issue by drmcclelland** [wojtpl2/ExtendedXmlSerializer#246]
I have a 2-part question:

1)  How would I configure to have `<Name />` emitted instead of `<Name></Name>` ?

2)  What configuration should I use to have the `<Name>` tag not even get emitted in the case that the Name property is an **empty string**?  I would actually like to configure this for all string properties (not just the Name).

I have tried all 4 variants of the EmitBehaviors (Always, NotDefault, Classic, Assigned), but I always get the following XML no matter what:

    <?xml version="1.0" encoding="utf-8"?><TestData><Name></Name></TestData>

My POCO:

    public class TestData
    {
        public string Name { get; set; }
    }

My test code:

    var serializer = new ConfigurationContainer()
                      .EnableImplicitTyping(typeof(TestData))
                      .Emit(EmitBehaviors.NotDefault)
                      .Create();

    serializer.Serialize(new TestData {Name = "" })

**Comment by Mike-EEE** [comment]
Alright, these are good questions.  To start, `Emit` is used for more of a global rule for emitting values.  This does not impact the format.  In order to do this would require an extension, which I put together for you here:

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/9011d884a08066e09af7c90d1ef10559d2a780ea/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue246Tests.cs#L38-L114

That might seem like a lot of code, but most of it is the decoration of the `IFormatWriter`, which could be wrapped in a region.

As for your first question, this is possible as well, I've provided two ways of doing this, first as a specific configuration to the member/property, and then as a global configuration to `string`:

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/9011d884a08066e09af7c90d1ef10559d2a780ea/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue246Tests.cs#L20-L35

However, please note that you are now changing the actual value being stored persisted to disk/stream.  That empty value is `string.Value`, but since there is no value there, it will default to `default(string)` which is `null`.  If that is OK with you, then it is ok with me. :)

**Comment by Mike-EEE** [comment]
Oh, I thought of another way to keep your `<Name />` from being emitted while also retaining its value when it is `string.Empty`:

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/41742952f9f7f514c45622fd7a323fe4672f9c7a/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue246Tests.cs#L38-L56

**Comment by drmcclelland** [comment]
Thanks so much!  Good sample code, and super-helpful-and-FAST   ⚡️   I understand what you're saying about null vs empty string - I'm just trying to keep my XML as concise as possible by sending only the elements/values needed by the other system.

**Comment by Mike-EEE** [comment]
Cool, happy to help!  👍
