### ISSUE TITLE
EnableParameterizedContent option returning empty objects

### ISSUE THREAD

**Issue by aspektxxx** [wojtpl2/ExtendedXmlSerializer#250]
Given the sample below when EnableParameterizedContent() option is applied, the serializer returns just object with default values even though the deserialization occurs.

```
public static void SerializeAndDeserialize()
        {
            var srl = new ConfigurationContainer()
                                            .EnableParameterizedContent()
                                            .Create();

            var dt = new DataHolder();
            dt.Lenght = 13;

            var data = srl.Serialize(dt);
            var obj = srl.Deserialize<DataHolder>(data);
        }

public class DataHolder
    {
        public int Lenght { get; set; } = 5;
    }
```

**Comment by Mike-EEE** [comment]
Good find, @aspektxxx ... I have posted a fix to the preview feed.

https://www.myget.org/F/wojtpl2/api/v3/index.json

This extension (`EnableParameterizedContent`) was a last-minute addition and has turned into one of the most powerful aspects of EXS.  Unfortunately, it has proven a challenge as some bugs have turned out around it and each change has made it more brittle.  Oh well, we'll dodge bullets for as long as we can. 😁

**Comment by aspektxxx** [comment]
Sorry, still not working on more complex example. I'm working on isolating small piece of code to reproduce, will get back to it on Monday.

**Comment by aspektxxx** [comment]
So its look like that regular public properties are ignored when parametrized constructor is used. As they are serialized, they should be also deserialized.

```
public static void SerializeAndDeserialize()
        {
            var srl = new ConfigurationContainer()
                                            .EnableParameterizedContent()
                                            .Create();

            var dt = new DataHolder(11);
            dt.Name = "my super holder";
            dt.Data.Add(3);
            dt.Data.Add(5);
            dt.Data.Add(7);

            var data = srl.Serialize(dt);
            var obj = srl.Deserialize<DataHolder>(data);
        }

        public class DataHolder
        {
            public DataHolder(int lenght)
            {
                Lenght = lenght;
                Data = new List<int>();
            }

            public int Lenght { get; }
            public List<int> Data { get; set; }
            public string Name { get; set; }
        }
```

**Comment by Mike-EEE** [comment]
Ah yes, indeed this is a limitation of the current design.  It's intended to be exclusively for immutable object serialization and we're following the rules established with protobuf-net:

https://blog.marcgravell.com/2011/08/automatic-serialization-whats-in-tuple.html

We do have another issue open in regards to this with #207 that is tagged as a help-wanted enhancement.  I personally have a problem implementing functionality that mixes immutable and mutable design (which is why I have not participated in addressing this), but if you (or someone) submits a PR to implement this functionality as an extension I can assist in getting it reviewed and committed.

**Comment by aspektxxx** [comment]
In that case we can close this issue. 

PS: As to requested help, I see a huge problem in missing documentation for developers. There should be at least high level description of the architecture and its modularity. Currently, anyone willing to help gets easily discouraged by the code complexity.

**Comment by Mike-EEE** [comment]
Valuable, accurate, and well-deserved feedback, @aspektxxx and is also captured in #189.  Sort of the problem we have here is that v3 is in development, so we wanted to put v2 into maintenance mode, or not really support its API (or documentation) too much as v3 might lead to breaking changes.  But then there's the risk that v3 might never get completed, so... 🤷‍♂️

We do the best we can with the resources we got.  If we're lucky enough to get another hot shot to go through and re-write this thing from scratch with better community involvement, that would be ideal, but rather unlikely.  Getting free labor for open source efforts is a difficult task, to say the least. :)
