### ISSUE TITLE
Show warning when an element is in XML that is not in the model

### ISSUE THREAD

**Issue by johanvergeer** [wojtpl2/ExtendedXmlSerializer#256]
I noticed that serialization just stops when an element is seen that is not recognized by the configuration. 

Is it possible to continue serialization, and show a warning or error when an unknown element is found in the XML? I do think that it should continue deserializing. This might occur when a user, or another program, inserts an element (or attribute) that is not recognized by the serializer.

Except when it finds an element that is really invalid according to the configuration. For example when a word is found in an element that should contain an integer.

**Comment by Mike-EEE** [comment]
Yeah this is a good question, @johanvergeer.   I looked into this, and we're fighting a couple issues here.

Primarily, XML reader suffers from a lot of issues.  The native XML reader is pretty difficult to work with, and as a result, our own reader suffers.  I didn't help it any by introducing my own set of issues on top of that, either.

Further, a couple considerations here.  First is that while a member by a name might not exist, the element name might still be valid because it's either a namespace (e.g. `xmlns`) or it might be the name of an element if the object being deserialized is a list.

If it's data validation that you are after, we offer an `EnableMemberExceptionHandling` method that is demonstrated in #214.  Outside of that, I am not sure how we can elegantly pass a warning to the developer in this case, as we are not using any sort of logging mechanism for simplicity and performance considerations.

We could introduce another extension that would allow the developer to know when a member is null, but you would have to also consider the `xmlns` and element/list scenarios if this were to happen.  Maybe in this case we don't care about these scenarios and we simply want a callback and let the end user decide.

Perhaps something like:

`new ConfigurationContainer().EnableMemberNullHandling(x => MyMethod(x));` where `x` would be the current reader context.

I am certainly open to any suggestions to further address this, as well.

**Comment by Mike-EEE** [comment]
I talked myself right into that solution, @johanvergeer. 😆  Check it out:

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/27502f21daf96c8c7c20887f6b7acef625e4dd13/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue256Tests.cs#L14-L29

Available from our preview feed:
https://www.myget.org/F/wojtpl2/api/v3/index.json

Please note that we updated our preview feed to .21, which may or may not cause caching issues.  If you run into problems, please try deleting any EXS version in your nuget cache folder.

**Comment by johanvergeer** [comment]
Hi @Mike-EEE,

This looks useful, but not really what I was looking for. I'll explain with an example:

```csharp
public class Subject
{
    public string Foo { get; set; }
}
```

```csharp
        [Fact]
        public void DeserializeWithMissingProperty()
        {
            var data = @"<?xml version=""1.0"" encoding=""utf-8""?>
<Subject xmlns=""clr-namespace:Parlando.Uniforms.Common.Unittests.Serialization;assembly=Parlando.Uniforms.Common.Unittests"">
    <Bar>Hello, Bar!</Bar>
    <Foo>Hello, Foo!</Foo>
</Subject>";
            var container = new ConfigurationContainer()
                .Create();

            var subject = container.Deserialize<Subject>(data);

            subject.Foo.Should().Be("Hello, Foo!");
        }
```

When I run this, `subject.Foo` is `null` instead of `"Hello, Foo!"`. But when I remove the `<Bar>` element from xml, or when I put it after the `<Foo>` element, the test passes.

What would be nice is something like:

```csharp
new ConfigurationContainer()
    .IgnoreUnknownElementsInXml()
    .Create()
    .Deserialize<Subject>(data);
```

And when we would like to get some feedback:

- I would say `continue` should be `true` when deserializing should continue when an unknown element is found, and false, when deserialization should stop.
- It would be nice when `e` can show the name, parent elements, and line number in the xml file.

```csharp
new ConfigurationContainer()
    .HandleUnknownElementsInXml(continue: true, e => logger.Warning(e.name))
    .Create()
    .Deserialize<Subject>(data);
```

**Comment by Mike-EEE** [comment]
Ah, so keeping in mind the messiness with how the reader is, we're restricted in how we can accomplish what you're after.  

However, everything that you are looking for is currently available if you call the `EnableReaderContext` method:

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/d3d5c30632c7ff9128fb2d14d21e3a80f00a4941/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue256Tests.cs#L36-L91

It's a little messy, but fundamentally all the elements that you are looking for (as I understand them) can be accessed as shown.  The problem with introducing `HandleUnknownElementsInXml` is that "unknown elements" in this case that we're talking about is specifically within member elements, and when you start talking about "unknown elements" in the case of lists and lists with their own members, things get especially tricky.

Hope that makes sense.  Let me know if you are unable to access information that you need, or if we need to dive in further.  I am not happy with how messy it is, but this is easily the area of the API that needs the most love, and one I am hoping to do so with v3.

**Comment by Mike-EEE** [comment]
This has been deployed to `2.1.21`: https://www.nuget.org/packages/ExtendedXmlSerializer/

Please let us know if you encounter any further issues/questions/concerns around this and we will do our best to assist you.

Closing for now. 👍
