### ISSUE TITLE
Properties set to null (or uninitialized) are not serialized

### ISSUE THREAD

**Issue by lruckman** [wojtpl2/ExtendedXmlSerializer#28]
Using version _1.5.0_ nuget package _ExtendedXmlSerializer_ on _.NET framework 4.6.1_

When serializing a class that has properties that have either not been set or have a value set to null, the property does not appear in the serialized XML.

For simple values such as string, date time I would expect an empty node to be included in the serialized data.

[Gist Sample](https://gist.github.com/lruckman/5831eadf25417171241e1cc0efcece2e)

**Comment by Mike-EEE** [comment]
Thanks for reporting this @lruckman.  We're looking at ways of configuring the XML output so that you can have control over the formatting.

I would like more information from you regarding this, if you can.  Is the expectation here from previous usage of the .NET XML serializer and/or expected standards?  From my take, it would seem the default output should be as concise as possible, not only from a data-transfer context, but also for human/readability perspective as well.

**Comment by lruckman** [comment]
Checking how XmlSerializer works confirms you're doing it the same way, uninitialized property does not get emitted so probably not an issue the way you're doing it. In the future though at the very least having some sort of configuration option I could set so that it would emit an empty node if I needed it to would suffice but for now I'm just going to close the issue.

**Comment by Mike-EEE** [comment]
OK cool, thanks @lruckman  for your input.  We will try to keep track of this in #22 and see if we can make it happen. 👍
