### ISSUE TITLE
Confusing Developer Experience When Unknown Assemblies Are Encountered

### ISSUE THREAD

**Issue by Mike-E-angelo** [wojtpl2/ExtendedXmlSerializer#558]
From this comment: https://github.com/ExtendedXmlSerializer/home/issues/543#issuecomment-948049560

Serializer still breaks when defaulting to fusion.dll.  In such cases we should default to `Assembly.LoadWithPartialName`.

**Comment by Mike-E-angelo** [comment]
OK I lied... one more adjustment for tonight. 😁

I looked over your assembly list and the only ones that seem like they might cause trouble are these:

```
"F:\Repos\Deployer\Deployer.Gui\bin\Debug\net5.0\runtimes\win7-x86\native\av_libglesv2.dll"
"F:\Repos\Deployer\Deployer.Gui\bin\Debug\net5.0\runtimes\win7-x64\native\av_libglesv2.dll"
"F:\Repos\Deployer\Deployer.Gui\bin\Debug\net5.0\runtimes\win-arm64\native\av_libglesv2.dll"
```

They _should_ work however, as `_` is an allowed character.  But who knows.

I've created a build that throws a more descriptive error message of the assembly causing problems here:
https://github.com/ExtendedXmlSerializer/home/pull/559#issuecomment-948088313

You can try running that and it will at least tell you which assembly is giving you grief.

**Comment by Mike-E-angelo** [comment]
Hey @SuperJMN I am getting a 404 on your provided link. :(

**Comment by SuperJMN** [comment]
I'm sorry! I forgot to make it public! Now it's fixed.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SuperJMN** [comment]
Ouch, that’s right. The XML was an old version! Is it the reason of the issue?

De: ***@***.***>
Enviado: jueves, 21 de octubre de 2021 12:04
Para: ***@***.***>
CC: José Manuel ***@***.***>; ***@***.***>
Asunto: Re: [ExtendedXmlSerializer/home] `fusion.dll` - Breaks with Certain Assemblies/Environment (`net5.0`/Uno) (Issue #558)


OK looks like your XML makes reference to a Deployer.Core.DeploymentLibrary assembly but a quick look suggests that it does not exist, and should in fact be Deployer.Library. Let me know how that sounds to you.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FExtendedXmlSerializer%2Fhome%2Fissues%2F558%23issuecomment-948455142&data=04%7C01%7C%7C194baab5f54a41bd996a08d9947a3360%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637704074837524553%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=V%2FBrSo2PbdNpOehI6iEsNuFGDKU1alGMmBnI9CUM3kg%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAXXHW56KTEJEHBRBVLXNEDUH7QTTANCNFSM5GMUQMAA&data=04%7C01%7C%7C194baab5f54a41bd996a08d9947a3360%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637704074837534545%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=a4%2B8Z%2FNZUViM0gnafa4Yw0wJDF4hVS%2FbmLLb1arMTls%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C194baab5f54a41bd996a08d9947a3360%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637704074837534545%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=f9Btv853%2FCfYwYaXaWtKxZ5fkOq%2FG57eWAxrOUj2qM8%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C194baab5f54a41bd996a08d9947a3360%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637704074837544538%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Y%2B4V49x5ej9HtlKrkkv7qHdj0uZwsosm4iyGgKdb5KU%3D&reserved=0>.

**Comment by Mike-E-angelo** [comment]
Thank you @SuperJMN. Much appreciated. 🙏
