### ISSUE TITLE
Reference with list

### ISSUE THREAD

**Issue by wojtpl2** [wojtpl2/ExtendedXmlSerializer#87]
In V2 list with reference object works differently.

You can see ExtendedXmlSerializer.Tests.Legacy.SerializationReferenceTest.SerializationListWithReference.

It is list with elements what have reference to other elements. Eg. First element has reference to other element in list.

**Comment by Mike-EEE** [comment]
Are you saying that this doesn't work in v2?  I have the corollary of the test you mention [passing here](https://github.com/wojtpl2/ExtendedXmlSerializer/blob/v2.0.0/test/ExtendedXmlSerializer.Tests/ExtensionModel/ReferencesExtensionTests.cs#L118-L146).  Are you saying that it is passing when it should be failing somewhere?

**Comment by wojtpl2** [comment]
It's work but xml is different.

**Comment by wojtpl2** [comment]
In V1 all elements have body (definition) in root list node. 

In V2 body of element is where is first use. If element has reference to another element then definition of second element is inside first element. 

I hope you can understand me .😉 Below pseudo xml's.

In version 1 Xml looks 

```xml
<list>
  <ele id=2>
    <id=2>
    <other ref=1>
  </ele>
  <ele id=1>
    <id=1>
  </ele>
</list>
```

Ver2:
```xml
<list>
  <ele id=2>
    <id=2>
    <other  id =1>
      <id = 1>
    </other>
  </ele>
  <ele ref= 1/>
</list>
```

**Comment by Mike-EEE** [comment]
Correct.  It is a different approach here, and takes the first encounter of an object as the identity object.  Conceptually that seems more straight-forward to me, and was also easier to implement. 👼 

We could possibly introduce a strategy mechanism here to determine how identities and references are emitted, but it would be some work.

**Comment by wojtpl2** [comment]
I have program to design tracks systems.

All tracks are connected and if I have List<track> then in v2 I have xml:

```
<list>
  <track id=1> 
	<joints>
	  <track id=2>
		<joints>
		  <track id=3>
		  </track>
		</joints>
	  </track>
	<joints>
  </track>
  <track ref=2 />
  <track ref=3 />
</list>

```

In V1 xml was simpler to read:
```
<list>
  <track id=1> 
	<joints>
	  <track ref=2>
		<joints>
		  <track id=3 />
		</joints>
	  </track>
	<joints>
  </track>
  <track id=2>
    <joints>
	  <track ref=3 />
	  </track>
	</joints>
  </track>
  <track id=3 />
</list>
```

**Comment by Mike-EEE** [comment]
Yeah that is a good point.  I suppose it comes down to where you expect to find the data, and also if you are going to read it.   If you are simply saving the file you might not care where/how the identity/reference is calculated.  But if you are reading it you are correct that the reader can expect the data to always "point down" later in the file.

So what happens with a list within a list (within a list)?  The outermost list (closest to the root) will always have the identity, correct?

I suggest that we make this a strategy that you can apply to the `ReferencesExtension`.

**Comment by wojtpl2** [comment]
List within list works correctly in v1. 
First is reserved ids from first list. Then items are serialized. If item has list (or is list) EXS reserve ids from this list and then serialize items from this list. 

It was implemented there: https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/src/ExtendedXmlSerializer/ExtendedXmlSerializer.cs#L141-L180

How can I applay the `ReferencesExtension`?

**Comment by Mike-EEE** [comment]
Ah!  You reminded me of why v2 is designed as it is.  In v1 (the code you point out), there are two iterations that occur over the list.  Iterating is expensive, so that is what I tried to prevent in v2, so that there is only one iteration over a list per serialization.

However, I think we should be able to have both so that users can choose.

So what I meant by apply extension, it would be something like this:

```
var strategy = new ScanListAheadStrategy(); // not sure of name yet, but this is v1
var serializer = new ExtendedConfiguration().Extend(new ReferencesExtension(strategy)).Create();
```

**Comment by wojtpl2** [comment]
It is great idea. 
In v1 change strategy was impossible. Now I see the advantage and strength of v2 👍

**Comment by Mike-EEE** [comment]
Cool. :)  Yes, I am very happy with the extension model!  Actually one of the coolest things about this new featureset.  All of the new functionality has been created through extensions.  In fact I looked into how many extensions we have now and there are 26!  Another reason to keep the name ExtendedXmlSerializer (for now. :))

So I have been looking into this.  I actually got the XML to write out OK.  However, reading is another matter.  Unfortunately because we use the `XmlReader` now (forward only), it is a bit of a mess now to get this to work as it did in v1.

However, all is not lost.  The work that I was planning on doing for #82 might help out here.  I will look into it and let you know.

**Comment by Mike-EEE** [comment]
Sweeeeeeeet... OK.  There is now very basic support for this with the latest changes.

Unfortunately the strategy pattern didn't work out well because we use extension methods to add the `ReferencesExtension`.  But it's easy enough to use (have to add a few extensions):

```
var serializer = new ExtendedConfiguration().Type<TestClassReference>()
					                           .EnableReferences(x => x.Id)
					                           .Configuration.Extend(ReaderContextExtension.Default, DeferredReferencesExtension.Default).Create();
```

(I'm calling this `DeferredReferencesExtension` for now... feedback welcomed!)

Here is what the XML now looks like with this extension enabled:

```
<?xml version="1.0" encoding="utf-8"?>
<TestClassReferenceWithList xmlns="clr-namespace:ExtendedXmlSerializer.Tests.TestObject;assembly=ExtendedXmlSerializer.Tests">
	<Parent xmlns:exs="https://github.com/wojtpl2/ExtendedXmlSerializer/v2" exs:type="TestClassReference" Id="1" />
	<All>
		<Capacity>4</Capacity>
		<TestClassReference Id="3">
			<ObjectA xmlns:exs="https://github.com/wojtpl2/ExtendedXmlSerializer/v2" exs:type="TestClassReference" exs:entity="1" />
			<ReferenceToObjectA xmlns:exs="https://github.com/wojtpl2/ExtendedXmlSerializer/v2" exs:type="TestClassReference" exs:entity="1" />
		</TestClassReference>
		<TestClassReference Id="4">
			<ObjectA xmlns:exs="https://github.com/wojtpl2/ExtendedXmlSerializer/v2" exs:type="TestClassReference" exs:entity="2" />
			<ReferenceToObjectA xmlns:exs="https://github.com/wojtpl2/ExtendedXmlSerializer/v2" exs:type="TestClassReference" exs:entity="2" />
		</TestClassReference>
		<TestClassReference Id="2">
			<ObjectA xmlns:exs="https://github.com/wojtpl2/ExtendedXmlSerializer/v2" exs:type="TestClassReference" exs:entity="1" />
			<ReferenceToObjectA xmlns:exs="https://github.com/wojtpl2/ExtendedXmlSerializer/v2" exs:type="TestClassReference" exs:entity="1" />
		</TestClassReference>
		<TestClassReference xmlns:exs="https://github.com/wojtpl2/ExtendedXmlSerializer/v2" exs:entity="1" />
	</All>
</TestClassReferenceWithList>
```

Please let me know if this looks good to you.  If so, feel free to close this issue.  Otherwise we will look into improving it further. 👍

**Comment by Mike-EEE** [comment]
Also, it is worth mentioning that `ReaderContextExtension` is a dependency of `DeferredReferencesExtension`.  For v3 (or v2.5?) we should look into a better way of handling this so that it is not required to specifically add it.

**Comment by Mike-EEE** [comment]
Wanted to ping on this issue.  Does this seem to be working as expected now?  Please feel free to confirm and close if so (when you get the chance, I know you are off on weekends!), otherwise please let me know any problems you run into.

**Comment by Mike-EEE** [comment]
*ping* :)  Is this good or no?

**Comment by wojtpl2** [comment]
I want to publish alpha 2. Do you have anything to push?

**Comment by wojtpl2** [comment]
Then I'll try it.

**Comment by Mike-EEE** [comment]
I pushed my changes last night, with basically renaming and reorganization on the write side.  I hope to get the read side later today.  You can definitely push an alpha 2 for now. :)

**Comment by Mike-EEE** [comment]
Well of course right after this I renamed the configuration from `ExtendedConfiguration` to `ConfigurationContainer`.   Hope this OK. 👼

**Comment by Mike-EEE** [comment]
OK I just now committed a bunch of changes for the file/folder/namespace organization of the project.  I would suggest making an alpha 2.1 if you can. 👍

**Comment by wojtpl2** [comment]
I've create 2.0.0-alpha3. Nuget don't support dot in alpha version. 
https://docs.microsoft.com/en-us/nuget/create-packages/prerelease-packages

**Comment by Mike-EEE** [comment]
Great!  Good enough. :)

**Comment by wojtpl2** [comment]
I'll try it next week.

**Comment by wojtpl2** [comment]
Update: I can't check it. I use #97.

**Comment by Mike-EEE** [comment]
Haha has _anything_ that you've tried work? :)

If you don't use a `System.Windows.Point` how does it look?

Also, please add this as another test so that I can make sure it works.

Unfortunately I have been caught up in upgrading to the latest Windows (Creator Update).  [I continue to have problems with Benchmark.NET times](https://github.com/dotnet/BenchmarkDotNet/issues/433)  so that has led me to essentially refreshing my environment to see if that helps.

I was also able to upgrade our project to VS2017 to get it to compile.  VS2017 compiles VERY FAST so that is awesome.  Unfortunately when I close the solution and open it back up it results in thinking that it is still .xproj files.  So I will need to figure out what is going on.  However, for the most part it seems to be OK. 👍

**Comment by wojtpl2** [comment]
I've added example in #97. 
I use V1.5 in my project and I use System.Windows.Point and other eg.: Color. Version 1.5 support this. It is simple struct with properties. It isn't something special object.
It isn't working in ExtnededXmlSerializer.Legacy.

**Comment by Mike-EEE** [comment]
Alright cool...thank you for getting all the information together.  My environment is not in working order right now and won't be for a while but I will certainly tackle this when I can and let you know what I find.

**Comment by wojtpl2** [comment]
Ok Thank you!

**Comment by Mike-EEE** [comment]
I think this is fixed now, yes? 😄

**Comment by Mike-EEE** [comment]
This is addressed in the latest version.  Please open a new issue if you find something that isn't working as expected.
